<h1>Some Panic/Recover Use Cases</h1>

<p>
Panic and recover have been
<a href="control-flows-more.html#panic-recover">introduced before</a>.
The following of the current article will introduce some (good and bad)
panic/recover use cases.
</p>

<a class="anchor" id="avoid-crashing"></a>
<h3>Use Case 1: Avoid Panics Crashing Programs</h3>

<div>
<p>
This should be the most popular use case of panic/recover.
The use case is used commonly in concurrent programs, especially client-server programs.
</p>

An example:
<pre class="line-numbers"><code class="language-go">package main

import "errors"
import "log"
import "net"

func main() {
	listener, err := net.Listen("tcp", ":12345")
	if err != nil {
		log.Fatalln(err)
	}
	for {
		conn, err := listener.Accept()
		if err != nil {
			log.Println(err)
		}
		// Handle each client connection
		// in a new goroutine.
		go ClientHandler(conn)
	}
}

func ClientHandler(c net.Conn) {
	defer func() {
		if v := recover(); v != nil {
			log.Println("capture a panic:", v)
			log.Println("avoid crashing the program")
		}
		c.Close()
	}()
	panic(errors.New("just a demo.")) // a demo-purpose panic
}
</code></pre>

<p>
Start the server and run <code>telnet localhost 12345</code> in another terminal,
we can observe that the server will not crash down
for the panics created in each client handler goroutine.
</p>

<p>
If we don't recover the potential panic in each client handler goroutine,
the potential panic will crash the program.
</p>

</div>

<a class="anchor" id="auto-restart"></a>
<h3>Use Case 2: Automatically Restart a Crashed Goroutine</h3>

<div>

When a panic is detected in a goroutine, we can create a new goroutine for it.
An example:
<pre class="line-numbers"><code class="language-go">package main

import "log"
import "time"

func shouldNotExit() {
	for {
		// Simulate a workload.
		time.Sleep(time.Second)

		// Simulate an unexpected panic.
		if time.Now().UnixNano() & 0x3 == 0 {
			panic("unexpected situation")
		}
	}
}

func NeverExit(name string, f func()) {
	defer func() {
		if v := recover(); v != nil {
			// A panic is detected.
			log.Println(name, "is crashed. Restart it now.")
			go NeverExit(name, f) // restart
		}
	}()
	f()
}

func main() {
	log.SetFlags(0)
	go NeverExit("job#A", shouldNotExit)
	go NeverExit("job#B", shouldNotExit)
	select{} // block here for ever
}
</code></pre>
</div>

<a class="anchor" id="long-jump"></a>
<h3>Use Case 3: Use <code>panic</code>/<code>recover</code> Calls to Simulate Long Jump Statements</h3>

<div>
<p>
Sometimes, we can use panic/recover as a way to
simulate crossing-function long jump statements
and crossing-function returns,
though generally this way is not recommended to use.
This way does harm for both code readability and execution efficiency.
The only benefit is sometimes it can make code look less verbose.
</p>

In the following example, once a panic is created in an inner function,
the execution will jump to the deferred call.
<pre class="line-numbers"><code class="language-go">package main

import "fmt"

func main() {
	n := func () (result int)  {
		defer func() {
			if v := recover(); v != nil {
				if n, ok := v.(int); ok {
					result = n
				}
			}
		}()

		func () {
			func () {
				func () {
					// ...
					panic(123) // panic on succeeded
				}()
				// ...
			}()
		}()
		// ...
		return 0
	}()
	fmt.Println(n) // 123
}
</code></pre>
</div>

<a class="anchor" id="avoid-verbose"></a>
<h3>Use Case 4: Use <code>panic</code>/<code>recover</code> Calls to Reduce Error Checks</h3>

<div>

An example:

<pre class="line-numbers"><code class="language-go">func doSomething() (err error) {
	defer func() {
		err, _ = recover().(error)
	}()

	doStep1()
	doStep2()
	doStep3()
	doStep4()
	doStep5()

	return
}

// In reality, the prototypes of the doStepN functions
// might be different. For each of them,
// * panic with nil for success and no needs to continue.
// * panic with error for failure and no needs to continue.
// * not panic for continuing.
func doStepN() {
	...
	if err != nil {
		panic(err)
	}
	...
	if done {
		panic(nil)
	}
}
</code></pre>

<p>
The above code is less verbose than the following one.
</p>

<pre class="line-numbers"><code class="language-go">func doSomething() (err error) {
	shouldContinue, err := doStep1()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep2()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep3()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep4()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep5()
	if !shouldContinue {
		return err
	}

	return
}

// If err is not nil, then shouldContinue must be true.
// If shouldContinue is true, err might be nil or non-nil.
func doStepN() (shouldContinue bool, err error) {
	...
	if err != nil {
		return false, err
	}
	...
	if done {
		return false, nil
	}
	return true, nil
}
</code></pre>


<!--
<pre class="line-numbers"><code class="language-go">func doSomething() (err error) {
package main

import "fmt"

func doTask(n int) {
	if n%2 != 0 {
		// Create a demo-purpose panic.
		panic(fmt.Errorf("bad number: %v", n))
	}
	return
}

func doSomething() (err error) {
	defer func() {
		// The second optional return must be present here,
		// otherwise, the assertion will panic if no errors occur.
		err, _ = recover().(error)
	}()

	doTask(22)
	doTask(98)
	doTask(100)
	doTask(53)
	return nil
}

func main() {
	fmt.Println(doSomething()) // bad number: 53
}
</code></pre>

<p>
The above code is less verbose than the following one.
</p>

<pre class="line-numbers"><code class="language-go">func doTask(n int) error {
	if n%2 != 0 {
		return fmt.Errorf("bad number: %v", n)
	}
	return nil
}

func doSomething() (err error) {
	err = doTask(22)
	if err != nil {
		return
	}
	err = doTask(98)
	if err != nil {
		return
	}
	err = doTask(100)
	if err != nil {
		return
	}
	err = doTask(53)
	if err != nil {
		return
	}
	return
}
</code></pre>
-->

<p>
However, usually, this panic/recover use pattern is not recommended to use.
It is less Go-idiomatic and less efficient.
</p>

And please note that, since a future Go version (probably Go 1.21),
a <code>panic(nil)</code> call will become
<a href="https://github.com/golang/go/issues/25448">eqivalent to <code>panic(new(runtime.PanicNilError))</code></a>.
Since then, the above deferred function call should be written as

<pre class="line-numbers"><code class="language-go">func doSomething() (err error) {
	defer func() {
		err, _ = recover().(error)
		if e := (*runtime.PanicNilError)(nil); errors.As(err, &e) {
			err = nil
		}
	}()

	doStep1()
	...
}
</code></pre>

<p>
</p>


</div>


